Controllers/LoginController.cs
using CalorieTrackerWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using CalorieTrackerAPI.Models;
using Newtonsoft.Json;

namespace CalorieTrackerWeb.Controllers
{
    public class LoginController : Controller
    {
        private readonly ISession session;

        public LoginController(IHttpContextAccessor httpContextAccessor)
        {
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(User u)
        {
            if(u.Email != null && u.Password != null)
            {
                LoginModel lm = new LoginModel(u.Email, u.Password);
                HttpClient httpClient = new HttpClient();
                StringContent s = new StringContent(JsonConvert.SerializeObject(lm),System.Text.Encoding.UTF8, "application/json");
                var response = await httpClient.PostAsync("https://localhost:7230/api/Login", s);
                if(response != null)
                {
                    if (response.IsSuccessStatusCode)
                    {
                        User curr = new User();
                        string content = await response.Content.ReadAsStringAsync();
                        curr = JsonConvert.DeserializeObject<User>(content); 
                        session.SetString("Username", curr.Name);
                        session.SetInt32("ID", curr.Id);
                        if (curr.Email == "admin@gmail.com")
                            session.SetString("Admin", "True");
                        TempData["success"] = "Login Successful";
                        return RedirectToAction("Index", "Home");
                    }
                }
                ModelState.AddModelError("", "Invalid User");
            }
            TempData["error"] = "Invalid User!";
            return View();
        }
        public IActionResult SignUp()
        {
            if (session.GetInt32("ID") != null)
            {
                session.Clear();
                TempData["warning"] = "You have been signed out!";
                return View();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(User user)
        {
            if (user != null)
            {
                if (user.Dob > DateTime.Now)
                {
                    TempData["error"] = "Invalid Date of Birth!";
                    return View();
                }
                HttpClient httpClient = new HttpClient();
                StringContent s = new StringContent(JsonConvert.SerializeObject(user), System.Text.Encoding.UTF8, "application/json");
                var response = await httpClient.PostAsync("https://localhost:7230/api/Users/Signup", s);
                if (response != null)
                {
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["success"] = "Account created successfully";
                        return RedirectToAction("Index");
                    }
                }
            }
            TempData["error"] = "Couldn't create account!";
            ModelState.AddModelError("","Invalid details!");
            return View();
        }
        public IActionResult SignOut()
        {
            session.Clear();
            TempData["success"] = "You have been logged out successfully!";
            return RedirectToAction("Index", "Home");
        }

    }
}

Controllers/WorkoutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CalorieTrackerWeb.Models;
using Newtonsoft.Json;

namespace CalorieTrackerWeb.Controllers
{
    public class WorkoutsController : Controller
    {
        private readonly ISession session;

        public WorkoutsController(IHttpContextAccessor httpContextAccessor)
        {
            session = httpContextAccessor.HttpContext.Session;
        }

        // GET: Workouts
        public async Task<IActionResult> Index()
        {
            if (session.GetInt32("ID") == null)
                return Unauthorized();
            int id = (int)session.GetInt32("ID");
            HttpClient client = new HttpClient();
            var response = await client.GetAsync("https://localhost:7230/api/Workouts?uid=" + id);
            if (response == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (response.IsSuccessStatusCode)
            {
                string s = await response.Content.ReadAsStringAsync();
                IEnumerable<Workout> workouts = JsonConvert.DeserializeObject<IEnumerable<Workout>>(s);
                return View(workouts);
            }
            return Unauthorized();
        }

        // GET: Workouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            HttpClient client = new HttpClient();
            var response = await client.GetAsync("https://localhost:7230/api/Workouts/" + id);
            if (response == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (response.IsSuccessStatusCode)
            {
                string s = await response.Content.ReadAsStringAsync();
                Workout workout = new();
                workout = JsonConvert.DeserializeObject<Workout>(s);
                if (workout == null)
                {
                    return NotFound();
                }
                return View(workout);
            }

            return View();
        }

        // GET: Workouts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Workouts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,WDateTime,Name,Calories")] Workout workout)
        {
            if (session.GetInt32("ID") == null)
                return Unauthorized();
            if (workout != null)
            {
                try
                {
                    workout.UserId = (int)session.GetInt32("ID");
                    HttpClient client = new HttpClient();
                    StringContent s = new StringContent(JsonConvert.SerializeObject(workout), System.Text.Encoding.UTF8, "application/json");
                    var response = client.PostAsync("https://localhost:7230/api/Workouts", s);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["error"] = "Error occurred while attempting to add entry!";
                    return View(workout);
                }
            }
            TempData["error"] = "Error occurred while attempting to add entry!";
            return View(workout);
        }

        // GET: Workouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            HttpClient client = new HttpClient();
            var response = await client.GetAsync("https://localhost:7230/api/Workouts/" + id);
            if (response == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (response.IsSuccessStatusCode)
            {
                string s = await response.Content.ReadAsStringAsync();
                Workout workout = new();
                workout = JsonConvert.DeserializeObject<Workout>(s);
                if (workout == null)
                {
                    return NotFound();
                }
                return View(workout);
            }
            return NotFound();
        }

        // POST: Workouts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,WDateTime,Name,Calories")] Workout workout)
        {
            if (id != workout.Id)
            {
                return NotFound();
            }
            if (workout.WDateTime == null)
                workout.WDateTime = DateTime.Now;
            if (workout.WDateTime > DateTime.Now)
            {
                TempData["error"] = "Date cannot be in the future!";
                return View(workout);
            }

            if (workout != null)
            {
                workout.UserId = (int)session.GetInt32("ID");
                HttpClient client = new HttpClient();
                StringContent s = new StringContent(JsonConvert.SerializeObject(workout), System.Text.Encoding.UTF8, "application/json");
                var response = await client.PutAsync("https://localhost:7230/api/Workouts/" + id, s);
                if (response == null)
                {
                    return RedirectToAction("Index", "Login");
                }
                if (response.IsSuccessStatusCode)
                {
                    TempData["success"] = "Details updated successfully";
                    return RedirectToAction("Index");
                }
            }
            TempData["error"] = "An error occurred!";
            return View(workout);
        }

        // GET: Workouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            HttpClient client = new HttpClient();
            var response = await client.GetAsync("https://localhost:7230/api/Workouts/" + id);
            if (response == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (response.IsSuccessStatusCode)
            {
                string s = await response.Content.ReadAsStringAsync();
                Workout workout = new();
                workout = JsonConvert.DeserializeObject<Workout>(s);
                if (workout == null)
                {
                    return NotFound();
                }
                return View(workout);
            }
            return NotFound();
        }

        // POST: Workouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id != null)
            {
                HttpClient client = new HttpClient();
                var response = await client.DeleteAsync("https://localhost:7230/api/Workouts/" + id);
                if (response == null)
                {
                    return RedirectToAction("Index", "Login");
                }
                if (response.IsSuccessStatusCode)
                {
                    TempData["success"] = "Entry deleted successfully";
                    return View("Index");
                }
            }
            TempData["error"] = "An error occurred!";
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CalorieTrackerWeb</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/CalorieTrackerWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/lux.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Calorie Tracker App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Dashboard">Dashboard</a>
                        </li>
                    </ul>
                    <partial name="_Login" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CalorieTrackerWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Login.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<ul class="navbar-nav">
    @{
        ViewBag.Username = @HttpContextAccessor.HttpContext.Session.GetString("Username");
        ViewBag.Admin = @HttpContextAccessor.HttpContext.Session.GetString("Admin");
    }
    @if (ViewBag.Username != null)
    {
        @if (ViewBag.Admin == "True")
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Users" asp-action="Index" title="List of users">List users</a>
            </li>
        }
        <li class="nav-item">
            <a class="nav-link" asp-controller="Users" asp-action="Details" title="Manage">Hello @ViewBag.Username !</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="FoodEntries" asp-action="Index" title="Add or view Food log">Food Log</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Workouts" asp-action="Index" title="Add or view Workouts">Workouts</a>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-controller="Login" asp-action="SignOut">
                <button type="submit" class="nav-link btn btn-link">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Login" asp-action="SignUp">Sign up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Login" asp-action="Index">Login</a>
        </li>
    }
</ul>

Views/Shared/_Notification.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["warning"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["warning"]');
    </script>
}